### ISSUE TITLE
Modifications for SEO

### ISSUE THREAD

**Issue by UroboTechnologies** [SaurabhBaranawal/uRoboTechnologies#2]
We need some changes in the content in order to improve site ranking on google.

**Comment by UroboTechnologies** [comment]
1. Change page title from "uRobo - Just What you need" to "Urobo Home Automation and Smarthomes"

**Comment by UroboTechnologies** [comment]
2. Please add 
twitter link : https://twitter.com/UroboSmarthome
homify link : https://www.homify.in/professionals/6003502/urobo-home-automation

**Comment by SaurabhBaranawal** [comment]
Changes done and committed.. ! Pick the build from here
