### ISSUE TITLE
Include Meta Description

### ISSUE THREAD

**Issue by UroboTechnologies** [SaurabhBaranawal/uRoboTechnologies#4]
<head>
  <meta name="description" content="Home Automation service providers in Delhi, Gurgaon, Noida. Smarthome consultants and Home Automation installation experts.">
</head>

**Comment by UroboTechnologies** [comment]
`<head>
  <meta name="description" content="Home Automation service providers in Delhi, Gurgaon/Gurugram, Noida and NCR. Smart Home, Home Automation and Home Security installation.">
</head>`

**Comment by SaurabhBaranawal** [comment]
Changes are committed!
